# PgBouncer User Password Configuration
# Based on: cloudy-old/db/pgbouncer.py::db_pgbouncer_set_user_password()

---
- name: Validate required parameters
  fail:
    msg: "Both 'user' and 'password' parameters are required"
  when: user is not defined or password is not defined

- name: Ensure userlist file exists
  file:
    path: /etc/pgbouncer/userlist.txt
    state: touch
    owner: postgres
    group: postgres
    mode: '0600'

- name: Check if user already exists in userlist
  shell: grep -q "^\"{{ user }}\"" /etc/pgbouncer/userlist.txt
  register: user_exists
  failed_when: false
  changed_when: false

- name: Remove existing user entry
  lineinfile:
    path: /etc/pgbouncer/userlist.txt
    regexp: "^\"{{ user }}\""
    state: absent
  when: user_exists.rc == 0

- name: Add user to PgBouncer userlist
  lineinfile:
    path: /etc/pgbouncer/userlist.txt
    line: "\"{{ user }}\" \"{{ password }}\""
    state: present
    owner: postgres
    group: postgres
    mode: '0600'
  notify: reload pgbouncer

- name: Display user addition success
  debug:
    msg: |
      ✅ PgBouncer user configured successfully
      User: {{ user }}
      Userlist: /etc/pgbouncer/userlist.txt
      Action: {{ 'Updated existing user' if user_exists.rc == 0 else 'Added new user' }}