# Granular Task: Change PostgreSQL User Password
# Equivalent to: cloudy-old/db/psql.py::db_psql_user_password()
# Usage: ansible-playbook tasks/db/postgresql/change-user-password.yml -e "username=myapp password=newsecret"

---
- name: Change PostgreSQL user password
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  vars:
    username: "{{ username | mandatory }}"
    password: "{{ password | mandatory }}"
    
  tasks:
    - name: Check if user exists
      become_user: postgres
      postgresql_query:
        query: "SELECT usename FROM pg_user WHERE usename = %s"
        positional_args:
          - "{{ username }}"
      register: pg_user_check
      
    - name: Fail if user does not exist
      fail:
        msg: "PostgreSQL user '{{ username }}' does not exist"
      when: pg_user_check.rowcount == 0
      
    - name: Change PostgreSQL user password
      become_user: postgres
      postgresql_user:
        name: "{{ username }}"
        password: "{{ password }}"
        encrypted: true
      register: pg_password_change
      
    - name: Display password change status
      debug:
        msg: |
          ✅ PostgreSQL user password changed
          Username: {{ username }}
          Status: {{ 'Password updated' if pg_password_change.changed else 'Password unchanged' }}
          Encrypted: Yes