# Granular Task: Set MySQL Root Password
# Equivalent to: cloudy-old/db/mysql.py::db_mysql_set_root_password()
# Usage: ansible-playbook tasks/db/mysql/set-root-password.yml -e "root_password=secure123"

---
- name: Set MySQL root password
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  vars:
    root_password: "{{ root_password | mandatory }}"
    
  tasks:
    - name: Validate root password is provided
      fail:
        msg: "Root password is required"
      when: not root_password or root_password == ""
      
    - name: Set MySQL root password using mysqladmin
      shell: "mysqladmin -u root password '{{ root_password }}'"
      register: mysql_root_password_set
      failed_when: false
      
    - name: Alternative method - Set root password using MySQL
      shell: |
        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ root_password }}'; FLUSH PRIVILEGES;"
      register: mysql_root_password_alt
      when: mysql_root_password_set.rc != 0
      failed_when: false
      
    - name: Test root password
      shell: "mysql -u root -p'{{ root_password }}' -e 'SELECT 1'"
      register: mysql_root_test
      changed_when: false
      failed_when: false
      
    - name: Display MySQL root password status
      debug:
        msg: |
          ✅ MySQL root password configuration completed
          Method: {{ 'mysqladmin' if mysql_root_password_set.rc == 0 else 'MySQL ALTER USER' }}
          Status: {{ 'Success' if mysql_root_test.rc == 0 else 'Failed - check password' }}
          Test: {{ 'Connected successfully' if mysql_root_test.rc == 0 else 'Connection failed' }}
          ⚠️  Remember to secure your MySQL installation with mysql_secure_installation