# Redis Password Configuration
# Based on: cloudy-old/sys/redis.py::sys_redis_configure_pass()

---
- name: Remove existing password configuration
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^requirepass .*'
    state: absent

- name: Set Redis password
  lineinfile:
    path: /etc/redis/redis.conf
    line: "requirepass {{ password }}"
    state: present
  when: password is defined and password != ""
  notify: restart redis

- name: Restart Redis service to apply password configuration
  systemd:
    name: redis-server
    state: restarted

- name: Display Redis password configuration success
  debug:
    msg: |
      ✅ Redis password configured successfully
      Password: {{ 'Set' if (password is defined and password != '') else 'Removed' }}
      Config: /etc/redis/redis.conf