# Granular Task: System Initialization
# Equivalent to: cloudy-old/sys/core.py::sys_init()
# Usage: ansible-playbook tasks/sys/core/init.yml

---
- name: System initialization
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  tasks:
    - name: Remove needrestart package to avoid unnecessary restarts
      apt:
        name: needrestart
        state: absent
      register: needrestart_removal
      failed_when: false
      
    - name: Clean up unused packages
      apt:
        autoremove: true
        autoclean: true
      when: needrestart_removal.changed
      
    - name: Display initialization status
      debug:
        msg: "✅ System initialization completed"