# Granular Task: Install Git
# Equivalent to: cloudy-old/sys/core.py::sys_git_install()
# Usage: ansible-playbook tasks/sys/core/install-git.yml

---
- name: Update package cache
  apt:
    update_cache: true
    
- name: Install git package
  apt:
    name: git
    state: present
  register: git_install_result
  
- name: Verify git installation
  command: git --version
  register: git_version
  changed_when: false
  
- name: Display git version
  debug:
    msg: "✅ Git installed successfully: {{ git_version.stdout }}"