# Granular Task: Reload Systemd Service
# Equivalent to: cloudy-old/sys/core.py::sys_reload_service()
# Usage: ansible-playbook tasks/sys/core/service-reload.yml -e "service_name=nginx"

---
- name: Reload systemd service
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  vars:
    # Required variable
    service_name: "{{ service_name | mandatory }}"
    
  tasks:
    - name: Reload service {{ service_name }}
      systemd:
        name: "{{ service_name }}"
        state: reloaded
      register: service_reload_result
      
    - name: Verify service status
      systemd:
        name: "{{ service_name }}"
      register: service_status
      
    - name: Display service status
      debug:
        msg: |
          ✅ Service {{ service_name }} reloaded successfully
          Status: {{ service_status.status.ActiveState }}
          Enabled: {{ service_status.status.UnitFileState | default('unknown') }}