# Granular Task: Start Systemd Service
# Equivalent to: cloudy-old/sys/core.py::sys_start_service()
# Usage: ansible-playbook tasks/sys/core/service-start.yml -e "service_name=nginx"

---
- name: Start systemd service
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  vars:
    # Required variable
    service_name: "{{ service_name | mandatory }}"
    
  tasks:
    - name: Start service {{ service_name }}
      systemd:
        name: "{{ service_name }}"
        state: started
      register: service_start_result
      
    - name: Verify service status
      systemd:
        name: "{{ service_name }}"
      register: service_status
      
    - name: Display service status
      debug:
        msg: |
          ✅ Service {{ service_name }} started successfully
          Status: {{ service_status.status.ActiveState }}
          Enabled: {{ service_status.status.UnitFileState | default('unknown') }}