# Update Package Repositories Tasks
# Equivalent to: cloudy-old/sys/core.py::sys_update()

---
- name: Update apt package cache
  apt:
    update_cache: true
    cache_valid_time: 0
  register: apt_update_result
  
- name: List upgradable packages
  shell: apt list --upgradable
  register: upgradable_packages
  changed_when: false
  failed_when: false
  
- name: Display update status
  debug:
    msg: "✅ Package repositories updated successfully"