# Initialize Git Tracking in /etc
# Based on: cloudy-old/sys/etc.py::sys_etc_git_init()

---
- name: Check if git is installed
  command: which git
  register: git_check
  failed_when: false
  changed_when: false

- name: Skip git operations if git not installed
  debug:
    msg: "Git not installed, skipping /etc git initialization"
  when: git_check.rc != 0

- name: Check if /etc is already a git repository
  stat:
    path: /etc/.git
  register: etc_git_check
  when: git_check.rc == 0

- name: Initialize git repository in /etc
  shell: |
    cd /etc
    git init
    git add .
    git commit -a -m "Initial Submission"
  when: 
    - git_check.rc == 0
    - not etc_git_check.stat.exists

- name: Display git initialization result
  debug:
    msg: |
      ✅ /etc git tracking initialized
      Repository: /etc/.git
      Status: {{ 'Already exists' if etc_git_check.stat.exists else 'Newly created' }}
  when: git_check.rc == 0