# Ansible Inventory - YAML Format
# This replaces the old .cloudy config files with structured inventory

all:
  children:
    # Server Types (matching old recipes)
    generic_servers:
      hosts:
        # example-generic:
        #   ansible_host: 10.10.10.198
        #   ansible_user: root
        #   ansible_port: 22
    
    database_servers:
      hosts:
        # example-db:
        #   ansible_host: 10.10.10.199
        #   ansible_user: admin
        #   ansible_port: 22022
    
    web_servers:
      hosts:
        # example-web:
        #   ansible_host: 10.10.10.200
        #   ansible_user: admin
        #   ansible_port: 22022
    
    cache_servers:
      hosts:
        # example-redis:
        #   ansible_host: 10.10.10.201
        #   ansible_user: admin
        #   ansible_port: 22022
    
    load_balancers:
      hosts:
        # example-lb:
        #   ansible_host: 10.10.10.202
        #   ansible_user: admin
        #   ansible_port: 22022

  vars:
    # Global defaults (from cloudy-old/cfg/defaults.cfg)
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3