# Test Inventory for All Simplified Workflows
# Step 1: ansible-playbook -i inventory/test.yml playbooks/recipes/core/security.yml 
# Step 2: ansible-playbook -i inventory/test.yml playbooks/recipes/core/base.yml
# Step 3: ansible-playbook -i inventory/test.yml playbooks/recipes/[category]/[service].yml

---
all:
  vars:
    # Global Settings
    git_user_full_name: "Test User"
    git_user_email: "test@example.com"
    timezone: "America/New_York"
    
    # Security Configuration
    admin_user: admin
    admin_password: secure123
    admin_groups: "admin,www-data"
    ssh_port: 22022
    setup_swap: false
    
    # Connection Settings
    ansible_host_key_checking: false
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_become_pass: secure123
    
  hosts:
    # Main test server - used for all recipes
    test-server:
      ansible_host: 10.10.10.198
      hostname: test-server.example.com
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      
      # Service-specific configs (when testing individual services)
      domain_name: test-server.example.com
      postgresql_version: "15"
      postgis_version: "3.3"
      database_port: 5432
      redis_memory_mb: 512
      redis_port: 6379
      webserver: gunicorn
      webserver_port: 8181