# Test Inventory for Recipe Testing
# Usage: ansible-playbook -i inventory/test-recipes.yml playbooks/recipes/[recipe-name].yml

---
all:
  vars:
    # Common Configuration (AFTER initial setup)
    ansible_user: root
    ansible_ssh_pass: pass4now
    ansible_ssh_private_key_file: ~/.ssh/id_rsa  # SSH key for admin user
    ansible_port: 22  # Changed SSH port
    ansible_host_key_checking: false
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # Global Settings
    git_user_full_name: "Test User"
    git_user_email: "test@example.com"
    timezone: "America/New_York"
    
  children:
    # Generic Servers (Foundation)
    generic_servers:
      hosts:
        test-generic:
          ansible_host: 10.10.10.198
          hostname: test-generic.example.com
          admin_user: admin
          admin_password: secure123
          ansible_become_pass: secure123
          admin_groups: "admin,www-data"
          ssh_port: 22022
          ssh_disable_root: true
          ssh_enable_password_auth: false
          swap_size: 512
          setup_swap: false
          
    # VPN Servers
    vpn_servers:
      hosts:
        test-vpn:
          ansible_host: 10.10.10.198
          hostname: vpn.example.com
          domain: vpn.example.com
          port: 1194
          proto: udp
          
    # Web Servers
    web_servers:
      hosts:
        test-web:
          ansible_host: 10.10.10.198
          hostname: web.example.com
          domain_name: web.example.com
          webserver: gunicorn
          webserver_port: 8181
          python_version: "3"
          pg_version: "15"
          
    # Database Servers
    database_servers:
      hosts:
        test-db:
          ansible_host: 10.10.10.198
          hostname: db.example.com
          postgresql_version: "15"
          postgis_version: "3.3"
          database_port: 5432
          pgbouncer: true
          
    # Cache Servers
    cache_servers:
      hosts:
        test-cache:
          ansible_host: 10.10.10.198
          hostname: cache.example.com
          port: 6379
          interface: "0.0.0.0"
          memory: 512  # MB
          password: "redis_secret_123"
          
    # Load Balancers
    load_balancers:
      hosts:
        test-lb:
          ansible_host: 10.10.10.198
          hostname: lb.example.com
          domain: app.example.com
          proto: https
          backends:
            - "10.10.10.200:8181"
            - "10.10.10.201:8181"
          ssl_cert_dir: "~/.ssh/certificates/"