# OpenVPN Create Client Configuration
# Based on: cloudy-old/sys/openvpn.py::sys_openvpn_docker_create_client()
# Create a new OpenVPN client and download its configuration

---
- name: Set OpenVPN Docker variables
  set_fact:
    docker_name: "{{ proto | default('udp') }}-{{ port | default('1194') }}.{{ domain }}"
    docker_data: "{{ datadir | default('/docker/openvpn') }}/{{ proto | default('udp') }}-{{ port | default('1194') }}.{{ domain }}"
    docker_repo: "{{ repo | default('kylemanna/openvpn') }}"

- name: Build client certificate (no passphrase)
  docker_container:
    name: "openvpn-client-{{ client_name }}-{{ docker_name }}"
    image: "{{ docker_repo }}"
    state: started
    detach: false
    auto_remove: true
    volumes:
      - "{{ docker_data }}:/etc/openvpn"
    command: "easyrsa build-client-full {{ client_name }} nopass"
  when: passphrase | default('nopass') == 'nopass'

- name: Build client certificate (with passphrase)
  docker_container:
    name: "openvpn-client-{{ client_name }}-{{ docker_name }}"
    image: "{{ docker_repo }}"
    state: started
    detach: false
    auto_remove: true
    volumes:
      - "{{ docker_data }}:/etc/openvpn"
    command: "easyrsa build-client-full {{ client_name }}"
    interactive: true
    tty: true
  when: passphrase | default('nopass') != 'nopass'

- name: Generate client configuration file
  docker_container:
    name: "openvpn-getclient-{{ client_name }}-{{ docker_name }}"
    image: "{{ docker_repo }}"
    state: started
    detach: false
    auto_remove: true
    volumes:
      - "{{ docker_data }}:/etc/openvpn"
    command: "ovpn_getclient {{ client_name }}"
  register: client_config

- name: Save client configuration to file
  copy:
    content: "{{ client_config.ansible_facts.docker_container.Output }}"
    dest: "/tmp/{{ client_name }}.ovpn"
    mode: '0600'

- name: Fetch client configuration to local machine
  fetch:
    src: "/tmp/{{ client_name }}.ovpn"
    dest: "{{ local_config_path | default('./') }}{{ client_name }}.ovpn"
    flat: yes
  when: download_config | default(true) | bool

- name: Remove temporary client config file
  file:
    path: "/tmp/{{ client_name }}.ovpn"
    state: absent

- name: Display client creation success
  debug:
    msg: |
      ✅ OpenVPN client created successfully
      Client: {{ client_name }}
      Container: {{ docker_name }}
      Config file: {{ local_config_path | default('./') }}{{ client_name }}.ovpn