# OpenVPN Revoke Client
# Based on: cloudy-old/sys/openvpn.py::sys_openvpn_docker_revoke_client()
# Revoke an OpenVPN client certificate

---
- name: Set OpenVPN Docker variables
  set_fact:
    docker_name: "{{ proto | default('udp') }}-{{ port | default('1194') }}.{{ domain }}"
    docker_data: "{{ datadir | default('/docker/openvpn') }}/{{ proto | default('udp') }}-{{ port | default('1194') }}.{{ domain }}"
    docker_repo: "{{ repo | default('kylemanna/openvpn') }}"

- name: Revoke client certificate
  docker_container:
    name: "openvpn-revoke-{{ client_name }}-{{ docker_name }}"
    image: "{{ docker_repo }}"
    state: started
    detach: false
    auto_remove: true
    volumes:
      - "{{ docker_data }}:/etc/openvpn"
    command: "easyrsa revoke {{ client_name }}"
    interactive: true
    tty: true

- name: Generate certificate revocation list
  docker_container:
    name: "openvpn-gencrl-{{ client_name }}-{{ docker_name }}"
    image: "{{ docker_repo }}"
    state: started
    detach: false
    auto_remove: true
    volumes:
      - "{{ docker_data }}:/etc/openvpn"
    command: "easyrsa gen-crl"

- name: Restart OpenVPN container to apply revocation
  docker_container:
    name: "{{ docker_name }}"
    state: started
    restart: true

- name: Display client revocation success
  debug:
    msg: |
      ✅ OpenVPN client revoked successfully
      Client: {{ client_name }}
      Container: {{ docker_name }}
      Status: Certificate revoked and CRL updated