# Granular Task: Add User to Passwordless Sudoers
# Equivalent to: cloudy-old/sys/user.py::sys_user_add_passwordless_sudoer()
# Usage: ansible-playbook tasks/sys/user/add-passwordless-sudoer.yml -e "username=automation"

---
- name: Add user to passwordless sudoers
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  vars:
    username: "{{ username | mandatory }}"
    
  tasks:
    - name: Add user to passwordless sudoers
      lineinfile:
        path: /etc/sudoers
        line: "{{ username }}   ALL=(ALL:ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
        backup: true
      register: passwordless_sudoers_result
      
    - name: Display passwordless sudoers status
      debug:
        msg: |
          ✅ User added to passwordless sudoers: {{ username }}
          Status: {{ 'Added' if passwordless_sudoers_result.changed else 'Already present' }}
          ⚠️  SECURITY WARNING: This user has passwordless root access!