# Granular Task: Change User Password
# Equivalent to: cloudy-old/sys/user.py::sys_user_change_password()
# Usage: ansible-playbook tasks/sys/user/change-password.yml -e "username=john password=newpass"

---
- name: Change user password
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  vars:
    # Required variables
    username: "{{ username | mandatory }}"
    password: "{{ password | mandatory }}"
    
  tasks:
    - name: Validate username is not root
      fail:
        msg: "Cannot change root password using this task"
      when: username == "root"
      
    - name: Change password for user {{ username }}
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: always
      register: password_change_result
      

      
    - name: Display success message
      debug:
        msg: "✅ Password successfully changed for user: {{ username }}"
      when: password_change_result.changed