# Nginx SSL Certificate Installation
# Based on: cloudy-old/web/nginx.py::web_nginx_copy_ssl()

---
- name: Create SSL directories for nginx
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/ssl/nginx/crt
    - /etc/ssl/nginx/key

- name: Check if local certificate directory exists
  stat:
    path: "{{ ssl_cert_dir | default('~/.ssh/certificates/') | expanduser }}"
  delegate_to: localhost
  register: cert_dir_check

- name: Fail if certificate directory doesn't exist
  fail:
    msg: "⚠️ Local certificate directory not found: {{ ssl_cert_dir | default('~/.ssh/certificates/') | expanduser }}"
  when: not cert_dir_check.stat.exists

- name: Check if certificate files exist locally
  stat:
    path: "{{ ssl_cert_dir | default('~/.ssh/certificates/') | expanduser }}/{{ domain }}.{{ item }}"
  delegate_to: localhost
  register: cert_files_check
  loop:
    - combo.crt
    - key
  failed_when: false

- name: Fail if certificate files don't exist
  fail:
    msg: |
      ⚠️ SSL certificate files not found:
      - {{ ssl_cert_dir | default('~/.ssh/certificates/') | expanduser }}/{{ domain }}.combo.crt
      - {{ ssl_cert_dir | default('~/.ssh/certificates/') | expanduser }}/{{ domain }}.key
  when: cert_files_check.results | selectattr('stat.exists', 'equalto', false) | list | length > 0

- name: Copy SSL certificate to server
  copy:
    src: "{{ ssl_cert_dir | default('~/.ssh/certificates/') | expanduser }}/{{ domain }}.combo.crt"
    dest: "/etc/ssl/nginx/crt/{{ domain }}.combo.crt"
    owner: root
    group: root
    mode: '0644'

- name: Copy SSL private key to server
  copy:
    src: "{{ ssl_cert_dir | default('~/.ssh/certificates/') | expanduser }}/{{ domain }}.key"
    dest: "/etc/ssl/nginx/key/{{ domain }}.key"
    owner: root
    group: root
    mode: '0600'

- name: Display SSL installation success
  debug:
    msg: |
      ✅ SSL certificates installed successfully for {{ domain }}
      Certificate: /etc/ssl/nginx/crt/{{ domain }}.combo.crt
      Private Key: /etc/ssl/nginx/key/{{ domain }}.key