# Granular Task: Allow Traffic from Specific Host on Specific Port
# Equivalent to: cloudy-old/sys/firewall.py::fw_allow_incoming_host_port()
# Usage: ansible-playbook tasks/sys/firewall/allow-host-port.yml -e "host=192.168.1.100 port=5432"

---
- name: Allow traffic from specific host on specific port
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  vars:
    host: "{{ host | mandatory }}"
    port: "{{ port | mandatory }}"
    
  tasks:
    - name: Validate port number
      fail:
        msg: "Port must be between 1-65535, got: {{ port }}"
      when: port | int < 1 or port | int > 65535
      
    - name: Allow traffic from {{ host }} to port {{ port }}
      ufw:
        rule: allow
        from_ip: "{{ host }}"
        to_port: "{{ port }}"
      register: ufw_allow_host_port
      
    - name: Get UFW status
      command: ufw status
      register: ufw_status
      changed_when: false
      
    - name: Display host/port allow status
      debug:
        msg: |
          ✅ Traffic allowed from {{ host }} to port {{ port }}
          Status: {{ 'Rule added' if ufw_allow_host_port.changed else 'Rule already exists' }}
          
          Current UFW Rules:
          {{ ufw_status.stdout }}