# Granular Task: Disable SSH Password Authentication
# Equivalent to: cloudy-old/sys/ssh.py::sys_ssh_disable_password_authentication()
# Usage: ansible-playbook tasks/sys/ssh/disable-password-auth.yml

---
- name: Disable SSH password authentication
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  tasks:
    - name: Disable password authentication in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+'
        line: "PasswordAuthentication no"
        backup: true
      register: password_auth_config
      
    - name: Reload SSH service
      systemd:
        name: ssh
        state: reloaded
      when: password_auth_config.changed
      
    - name: Display password authentication status
      debug:
        msg: |
          ✅ SSH password authentication disabled
          Config changed: {{ password_auth_config.changed }}
          ⚠️  Ensure SSH keys are configured before disconnecting!