# Granular Task: Enable SSH Password Authentication
# Equivalent to: cloudy-old/sys/ssh.py::sys_ssh_enable_password_authentication()
# Usage: ansible-playbook tasks/sys/ssh/enable-password-auth.yml

---
- name: Enable SSH password authentication
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  
  tasks:
    - name: Enable password authentication in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+'
        line: "PasswordAuthentication yes"
        backup: true
      register: password_auth_config
      
    - name: Reload SSH service
      systemd:
        name: ssh
        state: reloaded
      when: password_auth_config.changed
      
    - name: Display password authentication status
      debug:
        msg: |
          ✅ SSH password authentication enabled
          Config changed: {{ password_auth_config.changed }}
          ⚠️  Security note: Password authentication is now allowed