name: Test Ansible Cloudy

on:
  push:
    branches: [ main, dev, "feat/*", ansible-ify ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Ansible
      run: |
        pip install --upgrade pip
        pip install ansible
    
    - name: Navigate to Ansible implementation
      run: cd cloudy
    
    - name: Run Ansible syntax checks
      run: |
        cd cloudy
        # Test all recipe playbooks syntax
        find playbooks/recipes/ -name "*.yml" -exec ansible-playbook --syntax-check {} \;
        
        # Test main authentication flow
        ansible-playbook --syntax-check test-simple-auth.yml
        
        # Test inventory validation
        ansible-inventory -i inventory/test-recipes.yml --list > /dev/null
    
    - name: Run comprehensive test suite
      run: |
        cd cloudy
        ./test-runner.sh