# Apache2 Installation and Bootstrap
# Based on: cloudy-old/web/apache.py::web_apache2_install() and util_apache2_bootstrap()

---
- name: Install Apache2 web server
  package:
    name: apache2
    state: present

- name: Install Apache2 modules based on Python version
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ 'libapache2-mod-wsgi-py3' if (python_version | default('3')) == '3' else 'libapache2-mod-wsgi' }}"
    - libapache2-mod-rpaf

- name: Stop Apache2 service for configuration
  systemd:
    name: apache2
    state: stopped

- name: Remove default Apache2 configuration
  file:
    path: /etc/apache2
    state: absent

- name: Recreate Apache2 configuration directory
  file:
    path: /etc/apache2
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install main Apache2 configuration
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2

- name: Install Apache2 environment variables
  template:
    src: apache2-envvars.j2
    dest: /etc/apache2/envvars
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2

- name: Install Apache2 ports configuration
  template:
    src: apache2-ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2

- name: Create sites-available directory
  file:
    path: /etc/apache2/sites-available
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create sites-enabled directory
  file:
    path: /etc/apache2/sites-enabled
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Enable required Apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - mime
    - alias
    - rpaf
    - wsgi
  notify: restart apache2

- name: Start and enable Apache2 service
  systemd:
    name: apache2
    state: started
    enabled: true

- name: Display Apache2 installation success
  debug:
    msg: |
      ✅ Apache2 installed and configured successfully
      Status: Running and enabled
      Config: /etc/apache2/apache2.conf
      Sites: /etc/apache2/sites-available/ and /etc/apache2/sites-enabled/
      Modules: mod_wsgi, mod_rpaf, mod_mime, mod_alias enabled